In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)
torch.zeros([1])

tensor([0.])

In [3]:
import torch
from torch import nn
class LSTMClassifier(nn.Module):
    def __init__(self, batch_size, output_size, hidden_size, vocab_size, embedding_length, weights):
        super(LSTMClassifier, self).__init__()
        self.batch_size = batch_size
        self.output_size = output_size
        self.hidden_size = hidden_size
        self.vocab_size = vocab_size
        self.embedding_length = embedding_length
        self.word_embeddings = nn.Embedding(vocab_size, embedding_length)
        self.word_embeddings.weight = nn.Parameter(weights, requires_grad=False) 
        self.lstm = nn.LSTM(embedding_length, hidden_size) # Our main hero for this tutorial
        self.label = nn.Linear(hidden_size, output_size)
    def forward(self, input_sentence, batch_size=None):
        input = self.word_embeddings(input_sentence) 
        input = input.permute(1, 0, 2) 

        output, (final_hidden_state, final_cell_state) = self.lstm(input, (h_0, c_0))
        final_output = self.label(final_hidden_state[-1]) 
        
        return final_output
class Testmodel(nn.Module):
    def __init__(self, batch_size, output_size, hidden_size, vocab_size, embedding_length, weights):
        super(Testmodel, self).__init__()
        self.linear=nn.Linear(feature_size, embedding_length)  # feature size -->embedding_length  7->128
        self.lstm = nn.LSTM(embedding_length, hidden_size,3) # 128
        self.label = nn.Linear(hidden_size, output_size)
    def forward(self, input_sentence, batch_size=None):
        input = self.word_embeddings(input_sentence) 
        input = input.permute(1, 0, 2) 

        output, (final_hidden_state, final_cell_state) = self.lstm(input, (h_0, c_0))
        final_output = self.label(final_hidden_state[-1]) 
        

        return final_output

In [6]:

import torch
import torch.nn as nn

s=torch.randn(32,10,7)
linear=nn.Linear(7, 128)
lstm = nn.LSTM(128, 64, batch_first=True) 
linear2=nn.Linear(64, 6)
output=linear(s)
print(output.shape)
outputs,(h,c)=lstm(output)
print(h.shape)
print(outputs.shape)

print('s',torch.cat((outputs,h.permute(1,0,2)),1))
# 
h=h[0]
print(h.shape)
# print(c.shape)
outputs=linear2(outputs)
print(outputs.shape)

torch.Size([32, 10, 128])
torch.Size([1, 32, 64])
torch.Size([32, 10, 64])
s tensor([[[-3.5168e-02, -2.1452e-02,  1.4242e-04,  ...,  3.2426e-02,
          -2.7741e-02,  1.0510e-01],
         [-1.3028e-03,  1.7763e-02,  1.4465e-02,  ...,  7.6372e-02,
          -8.6826e-02,  3.6860e-02],
         [ 9.6209e-02, -3.1612e-01, -1.8622e-01,  ...,  1.6104e-01,
          -3.8360e-02,  2.4354e-02],
         ...,
         [-1.2101e-01, -7.9423e-02, -1.0595e-01,  ...,  5.9498e-02,
          -2.1532e-01, -2.6307e-01],
         [-1.6557e-01,  2.4779e-02, -1.6936e-01,  ..., -8.4219e-02,
          -1.5375e-01, -5.2545e-02],
         [-1.6557e-01,  2.4779e-02, -1.6936e-01,  ..., -8.4219e-02,
          -1.5375e-01, -5.2545e-02]],

        [[ 2.6933e-03, -2.7554e-02,  1.2789e-01,  ...,  1.2416e-01,
          -4.5752e-02,  4.1609e-02],
         [-9.9709e-02,  3.8280e-02,  1.1226e-01,  ...,  1.4325e-01,
          -1.1883e-01, -5.1381e-02],
         [-1.0606e-01,  4.6399e-02,  8.5519e-02,  ...,  1.3764e-01,

In [10]:

import torch
import torch.nn as nn
input_dim = 17
hidden_dim = 64
output_dim = 17
num_layers = 2
s=torch.randn(32,10,17)
model = Seq2Seq(input_dim, hidden_dim, output_dim, num_layers)
output=linear(s)
print(output.shape)
outputs,(h,c)=lstm(output)
print(h.shape)
print(outputs.shape)
# 
h=h[0]
print(h.shape)
# print(c.shape)
outputs=linear2(h)
print(outputs.shape)

torch.Size([32, 10, 128])
torch.Size([1, 32, 64])
torch.Size([32, 10, 64])
torch.Size([32, 64])
torch.Size([32, 6])


In [2]:
lstm = nn.LSTM(3, 3)  # 输入维度为3维，输出维度为3维
inputs = [torch.randn(1, 3) for _ in range(5)]  # 生成一个长度为5的序列
s=torch.randn(5, 6)
linear=nn.Linear(6, 120)


# 初始化隐藏状态.
hidden = (torch.randn(1, 1, 3),
          torch.randn(1, 1, 3))
for i in inputs:
    # 将序列中的元素逐个输入到LSTM.
    # 经过每步操作,hidden 的值包含了隐藏状态的信息.
    out, hidden = lstm(i.view(1, 1, -1), hidden)

# 另外我们可以对一整个序列进行训练.
# LSTM第一个返回的第一个值是所有时刻的隐藏状态
# 第二个返回值是最后一个时刻的隐藏状态
#(所以"out"的最后一个和"hidden"是一样的)
# 之所以这样设计:
# 通过"out"你能取得任何一个时刻的隐藏状态，而"hidden"的值是用来进行序列的反向传播运算, 具体方式就是将它作为参数传入后面的 LSTM 网络.

# 增加额外的第二个维度.
inputs = torch.cat(inputs).view(len(inputs), 1, -1)
hidden = (torch.randn(1, 1, 3), torch.randn(1, 1, 3))  # 清空隐藏状态. 
out, hidden = lstm(inputs, hidden)
print(out)
print(hidden)

tensor([[[-0.0187,  0.1713, -0.2944]],

        [[-0.3521,  0.1026, -0.2971]],

        [[-0.3191,  0.0781, -0.1957]],

        [[-0.1634,  0.0941, -0.1637]],

        [[-0.3368,  0.0959, -0.0538]]], grad_fn=<StackBackward0>)
(tensor([[[-0.3368,  0.0959, -0.0538]]], grad_fn=<StackBackward0>), tensor([[[-0.9825,  0.4715, -0.0633]]], grad_fn=<StackBackward0>))


In [13]:
import numpy as np
trans_q=np.random.uniform(-1,1,(3))
trans_q

array([ 0.9433054 , -0.15332139,  0.41248861])